SCI Firewall Tests for macOS
vastlimits/uberAgent-config pull request #178
Opened 2024-01-10 22:46 UTC by vl-federico

Provide utility functions for consistent JSON reporting of test results and errors. Note that the `yq(1)` is required to run the tests.

Please review the test names, display names, descriptions, scores and risk scores thoroughly ensuring consistency with the Windows version!

Here is a sample successful output:
```
[
  {
    "Name": "FWEnabled",
    "DisplayName": "Firewall enabled",
    "Description": "Checks whether the macOS firewall is enabled.",
    "Score": 10,
    "RiskScore": 100,
    "ResultData": {
      "Enabled": true
    }
  },
  {
    "Name": "FWBlockAll",
    "DisplayName": "Firewall block-all rule active",
    "Description": "Checks whether the block-all rule of the macOS firewall is active.",
    "Score": 3,
    "RiskScore": 70,
    "ResultData": {
      "Enabled": false
    }
  },
  {
    "Name": "FWBlockAll",
    "DisplayName": "Firewall block-all rule active",
    "Description": "Checks whether the block-all rule of the macOS firewall is active.",
    "Score": 3,
    "RiskScore": 70,
    "ResultData": {
      "Enabled": false
    }
  },
  {
    "Name": "FWStealthMode",
    "DisplayName": "Firewall stealth mode active",
    "Description": "Checks whether the stealth mode of the macOS firewall is active.",
    "Score": 2,
    "RiskScore": 80,
    "ResultData": {
      "Enabled": false
    }
  },
  {
    "Name": "FWApprovedApps",
    "DisplayName": "Firewall approved applications",
    "Description": "Provides a list of applications that may accept incoming connections.",
    "Score": 10,
    "RiskScore": 0,
    "ResultData": "{\"ApprovedApplications\":[\"/Applications/Spotify.app\",\"/System/Library/CoreServices/ControlCenter.app\",\"/Applications/Focusrite Control.app/Contents/Library/LoginItems/FocusriteControlServer.app\",\"/Applications/Telephone.app\",\"/Applications/Logic Pro X.app\",\"/Applications/zoom.us.app/Contents/Frameworks/airhost.app\",\"/System/Library/CoreServices/RemoteManagement/ARDAgent.app\"]}"
  }
]
```

Here is a sample output containing errors:
```
[
  {
    "Name": "FWEnabled",
    "DisplayName": "Firewall enabled",
    "Description": "Checks whether the macOS firewall is enabled.",
    "ErrorCode": 255,
    "ErrorMessage": "socketfilterfw: unrecognized option `--getglo2balstate'"
  },
  {
    "Name": "FWBlockAll",
    "DisplayName": "Firewall block-all rule active",
    "Description": "Checks whether the block-all rule of the macOS firewall is active.",
    "ErrorCode": 255,
    "ErrorMessage": "socketfilterfw: unrecognized option `--getbloc2kall'"
  },
  {
    "Name": "FWStealthMode",
    "DisplayName": "Firewall stealth mode active",
    "Description": "Checks whether the stealth mode of the macOS firewall is active.",
    "ErrorCode": 255,
    "ErrorMessage": "socketfilterfw: unrecognized option `--gets2tealthmode'"
  },
  {
    "Name": "FWApprovedApps",
    "DisplayName": "Firewall approved applications",
    "Description": "Provides a list of applications that may accept incoming connections.",
    "ErrorCode": 255,
    "ErrorMessage": "socketfilterfw: unrecognized option `--li2stapps'"
  }
]
```

2024-01-11 22:05 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +    "FWBlockAll" \
That was a copy+paste error.

2024-01-11 22:14 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +    "Firewall enabled" \
I added a prefix to both the test name and the display name for all tests on b739286369e95133d6eace2bffd93b1e6ddbcd93. Let me know if that works for you!

2024-01-11 22:14 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +    "Firewall enabled" \
I added a prefix to both the test name and the display name for all tests on b739286369e95133d6eace2bffd93b1e6ddbcd93. Let me know if that works for you!

2024-01-11 22:15 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +    "FWEnabled" \
See f40069c176c90cf8d6d1580792449b98ad14e9ab.

2024-01-11 22:24 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +    "Firewall enabled" \
As discussed on gchat, I removed the name prefixes in 4acbbeefa621ae8477bf57f7e9a2ffade763e2ab.

2024-01-11 22:24 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +    "FWEnabled" \
As discussed on gchat, I removed the name prefixes in 4acbbeefa621ae8477bf57f7e9a2ffade763e2ab.

2024-01-12 10:40 UTC, martin-kretzschmar commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +  local expectedOutput="enabled"
`enabled` seems to be the wrong expected result to identify the state.

2024-01-12 10:49 UTC, martin-kretzschmar requested changes

2024-01-12 10:49 UTC, martin-kretzschmar commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +  vlRunCommand /usr/libexec/ApplicationFirewall/socketfilterfw --listapps
In my test `/usr/libexec/ApplicationFirewall/socketfilterfw --listapps` returns:

```ALF: total number of apps = 6

1 :  /System/Library/CoreServices/RemoteManagement/ARDAgent.app
 	 ( Allow incoming connections )

2 :  /System/Library/CoreServices/ControlCenter.app
 	 ( Allow incoming connections )

3 :  /opt/homebrew/Cellar/iperf3/3.15/bin/iperf3
 	 ( Allow incoming connections )

4 :  /opt/homebrew/Cellar/netcat/0.7.1/bin/netcat
 	 ( Allow incoming connections )

5 :  /Applications/Elgato Stream Deck.app
 	 ( Allow incoming connections )

6 :  /Library/Application Support/Logitech.localized/LogiOptionsPlus/logioptionsplus_agent.app
 	 ( Allow incoming connections )
```

While the script output shows:

```  {
    "Name": "FWApprovedApps",
    "DisplayName": "macOS Firewall approved applications",
    "Description": "Provides a list of applications that may accept incoming connections.",
    "Score": 10,
    "RiskScore": 0,
    "ResultData": "{\"ApprovedApplications\":[\"/System/Library/CoreServices/RemoteManagement/ARDAgent.app\",\"/System/Library/CoreServices/ControlCenter.app\",\"/opt/homebrew/Cellar/iperf3/3.15/bin/iperf3\",\"/opt/homebrew/Cellar/netcat/0.7.1/bin/netca\",\"/Applications/Elgato Stream Deck.app\",\"/Library/Application Support/Logitech.localized/LogiOptionsPlus/logioptionsplus_agent.app\"]}"
  }
```
```suggestion
  vlRunCommand /usr/libexec/ApplicationFirewall/socketfilterfw --listapps
```

Notice the missing "t" in `netca`.

2024-01-12 13:56 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +  local expectedOutput="enabled"
Good catch! See 5f5f00020082c29842c3ff983bf1d21d277a7f99.

2024-01-12 14:40 UTC, vl-federico commented on config/Security inventory/macOS/Firewall/Firewall.zsh
> +  vlRunCommand /usr/libexec/ApplicationFirewall/socketfilterfw --listapps
Good catch! Fixed in daa2c1f648b2355cc36a5f5583b5ab737e2f3831

2024-01-12 16:39 UTC, martin-kretzschmar approved these changes

2024-01-12 16:47 UTC, merged