Check configuration (and archive) using uAConfigCheck before publishing
vastlimits/uberAgent-config pull request #184
Opened 2024-01-18 16:14 UTC by ccomendant

Use the `uAConfigCheck`-tool in the "Create archive" pipeline to check the resulting configuration bundle before commiting it to the repository.

2024-01-22 10:26 UTC, svnscha requested changes

2024-01-23 09:50 UTC, ccomendant commented on .github/workflows/ValidateConfig.yml
> +        .\uAConfigCheck.exe -t -w -v develop -f .\config\uberAgent.conf
@svnscha, hier "develop" bezieht sich auf die Version von der DLL, nicht den Branch in diesem Repo.

2024-01-23 09:52 UTC, ccomendant commented on .github/workflows/ValidateConfig.yml
> +        .\uAConfigCheck.exe -t -w -v develop -f .\config\uberAgent.conf
OK, jetzt verstehe ich, was Du meinst.

2024-01-23 09:54 UTC, ccomendant commented on .github/workflows/CreateArchive.yml
> +          az artifacts universal download --organization https://dev.azure.com/vastlimits \
@svnscha, ich weiß nicht wie sinnvoll das hier ist, da es hier um den Repo in Azure DevOps geht. D.h. man müsste in einem separaten Konto noch die Artifakten von uAConfigCheck nachbauen.

2024-01-31 08:56 UTC, merged