B801: add macOS SCI tests for local users and groups
vastlimits/uberAgent-config pull request #214
Opened 2024-04-05 08:35 UTC by dev-sai-collab

This PR adds SCI tests for local users and groups under macOS.
It checks:
- If auto logon is enabled/disabled (test name: "AutoLoginStatus")
- If a list of users is presented on the login screen or the user name must be entered manually (test name: "UserNamesShownOnLogin")
- If Apple's insecure default password policy is in use (test name: "DefaultPasswordPolicyUsed")
- If the guest account is enabled/disabled (test name: "GuestAccountEnabled")
- If the currently logged-in user (as in GUI) is a member of the admin group (test name: "CurrentUserAdmin")
- If the root user is enabled/disabled (test name: "RootUserEnabled")

2024-04-08 11:16 UTC, martin-kretzschmar requested changes

2024-04-08 11:16 UTC, martin-kretzschmar commented on config-dev/Security inventory/macOS/UsersAndGroups/LocalUsersAndGroups.zsh
> +vlCheckCurrentUserAdmin()
There is a check for Windows already:
`LocalUsersAndGroups	Local user is admin`

2024-04-09 10:27 UTC, martin-kretzschmar requested changes

2024-04-09 10:27 UTC, martin-kretzschmar commented on config-dev/Security inventory/Windows/LocalUserAndGroups/LocalUsersAndGroups-User.ps1
> +         Description  = "Windows: This test determines whether the local user is a member of the local Administrators group.\nmacOS: This test determines if the current user is a member of the group
"\n" does not work in Splunk.

2024-04-09 10:27 UTC, martin-kretzschmar commented on config-dev/Security inventory/macOS/LocalUsersAndGroups/LocalUsersAndGroups-User.zsh
> +  local testDescription="Windows: This test determines whether the local user is a member of the local Administrators group.\nmacOS: This test determines if the current user is a member of the group
"\n" does not work in Splunk.

2024-04-09 10:35 UTC, dev-sai-collab commented on config-dev/Security inventory/macOS/UsersAndGroups/LocalUsersAndGroups.zsh
> +vlCheckCurrentUserAdmin()
Done.

2024-04-09 10:35 UTC, dev-sai-collab commented on config-dev/Security inventory/Windows/LocalUserAndGroups/LocalUsersAndGroups-User.ps1
> +         Description  = "Windows: This test determines whether the local user is a member of the local Administrators group.\nmacOS: This test determines if the current user is a member of the group
Done.

2024-04-09 10:35 UTC, dev-sai-collab commented on config-dev/Security inventory/macOS/LocalUsersAndGroups/LocalUsersAndGroups-User.zsh
> +  local testDescription="Windows: This test determines whether the local user is a member of the local Administrators group.\nmacOS: This test determines if the current user is a member of the group
Done.

2024-04-09 10:50 UTC, merged