macOS: Adapt SCI Certificate Tests Names and ResultData to match Windows
vastlimits/uberAgent-config pull request #222
Opened 2024-04-18 14:13 UTC by vl-federico

See the updated [test protocol](https://podio.com/uberagentcom/uberagent-dev/apps/test-protocols/items/591) for sample output.

2024-04-19 09:35 UTC, martin-kretzschmar requested changes

2024-04-19 09:35 UTC, martin-kretzschmar commented on config-dev/Security inventory/macOS/Certificates/Certificates.zsh
> +      certObj=$( vlAddResultValue "${certObj}" "Issuer" "$issuer" )
Can we alter the formatting to, e.g., `CN=some-cn, DC=some-dc, DC=another-dc, DC=final-dc`?

2024-04-19 09:35 UTC, martin-kretzschmar commented on config-dev/Security inventory/macOS/Certificates/Certificates.zsh
> +  local testDisplayName="Certificates trusted by macOS - Machine"
Overall test category name needs to be `Certificate`.

2024-04-19 09:35 UTC, martin-kretzschmar commented on config-dev/Security inventory/macOS/Certificates/Certificates.zsh
> +      if [[ -n "$username" ]]; then
Scope determination needs a double-check. Always returns `Machine` during my tests.

2024-04-19 09:38 UTC, vl-federico commented on config-dev/Security inventory/macOS/Certificates/Certificates.zsh
> +  local testDisplayName="Certificates trusted by macOS - Machine"
Sorry, I don't quite understand what you mean. Do you mean to modify the testName to "CertificateTrByMac"?

2024-04-19 10:18 UTC, vl-federico commented on config-dev/Security inventory/macOS/Certificates/Certificates.zsh
> +  local testDisplayName="Certificates trusted by macOS - Machine"
Fixed in d232bd194a3d71b5c20b8e1a3d98724f0672a0b2.

2024-04-19 10:45 UTC, vl-federico commented on config-dev/Security inventory/macOS/Certificates/Certificates.zsh
> +      if [[ -n "$username" ]]; then
Fixed in 30bb39b6311c12ded8e7cf72aedaf0a37c084ca4. Also ensured that an empty certificate list results in the username being sent as `ResultData`.

2024-04-22 15:14 UTC, vl-federico commented on config-dev/Security inventory/macOS/Certificates/Certificates.zsh
> +      certObj=$( vlAddResultValue "${certObj}" "Issuer" "$issuer" )
Using the root CA for vastlimits, I created a fix in 556bf069c11227dcc310c8810b679db0b6e2b49d.

2024-04-24 14:47 UTC, vl-federico commented
@martin-kretzschmar Removed the `Scope` attribute, as discussed with Helge today in the [R&D meeting](https://podio.com/uberagentcom/intranet/apps/meetings/items/1144).

2024-04-25 07:26 UTC, martin-kretzschmar approved these changes

2024-04-25 07:36 UTC, merged